### ISSUE TITLE
实验疑惑

### ISSUE THREAD

**Issue by Deeachain** [zhengwang100/RECT#1]
你好，@zhengwang100 
昨天误删了问题
生成图中节点Embedding使用数据集是移除了unseen类别，SVM训练和验证节点分类使用数据集是完成类别的数据？

**Comment by zhengwang100** [comment]
Yes, when performing the classification testing (on all the classes), we used the labeled data of all classes (i.e., L); otherwise we cannot classify (recognize) the nodes coming from the unseen classes. This is a “cannot but” experimental setting.

Of course, you can also only test the classification ACC on the seen classes, with the completely-imbalanced labeled data (i.e., L').

Hope this would help you.

**Comment by zhengwang100** [comment]
About the second question.
In our table 3, we say "In the case of no node features, the best result is marked with underline."
Therefore, RECT is not in this case, as it use both features and graph structure information.

**Comment by Deeachain** [comment]
好的，了解了，谢谢解答

**Comment by zhengwang100** [comment]
您好，很高兴你能对我的论文以及代码感兴趣，我也积极回答了你的疑问，希望对你有所帮助。


您好像把问题删掉了？这里有个小小的愿望，您能不能把自己的问题继续展示给大家，最好是英文？这样您的问题和我们的回答能够帮助更多的人学习。这就像TensorFlow和Pytorch一样，用户的疑问和开发者的回答都会帮助到后来的人。


祝好，


zheng



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Deeachain <notifications@github.com&gt;
发送时间: 2020年8月26日 16:59
收件人: zhengwang100/RECT <RECT@noreply.github.com&gt;
抄送: Zheng Wang <554155317@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[zhengwang100/RECT] 实验疑惑 (#1)





 
好的，了解了，谢谢解答

**Comment by Deeachain** [comment]
> About the second question.
> In our table 3, we say "In the case of no node features, the best result is marked with underline."
> Therefore, RECT is not in this case, as it use both features and graph structure information.
表3这里的画横线部分如何理解，information中显示是有X的，为何还能参与no node feature的对比
![image](https://user-images.githubusercontent.com/58386037/91380808-74a5a400-e858-11ea-9f3b-991341a9eb1b.png)

**Comment by zhengwang100** [comment]
Might be lapsus calami. 
The numbers explain the results more rigorous~
